config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  #
  # Post route
  root 'posts#index'
  get '/post/:id' => "posts#show", as: :show
end

app/models/admin_user.rb
class AdminUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :posts
end

app/models/label.rb
class Label < ApplicationRecord
  has_many :posts
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :category
  belongs_to :label
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post,only:[:show]
  def index

    @post= if params[:search]
             Post.where('"title" LIKE ? or "body" LIKE ?',"%#{params[:search]}%","%#{params[:search]}%").paginate(page: params[:page], per_page: 4)
            elsif params[:searchCateg]
              Post.where(category_id: params[:searchCateg][:searchCateg]).paginate(page: params[:page], per_page: 4)
           else

             Post.paginate(page: params[:page], per_page: 4)
           end

  end

  def show

  end

  private

  def set_post
    @post = Post.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>CorotosBlogProject</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "tailwind", "inter-font", "data-turbo-track": "reload" %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>

  <div class="principal">
     <header class="navbar">
       <div class="container">
         <div class="row align-list">
           <div class="col-md-8 logo">
             <h1 class="font-bold text-4xl text-blue-500 f"><%=link_to 'CorotosBlog',root_path %></h1>
           </div>
           <div class="col-md-4">
             <ul class="list">
               <li>
                 <%= link_to 'Posts' ,root_path %>
               </li>
               <li>
                 <%= link_to 'Login',new_admin_user_session_path %>
               </li>
             </ul>
           </div>
         </div>
       </div>
     </header>
  </div>





    <main class="container mx-auto mt-28 px-5 flex ">
      <%= yield %>
    </main>
  </body>


  <footer class="">
    <div class="footer">
    <p>Autor: Jonathan Castillo<br>
      <a href="https://github.com/jonavero/hbtoons/tree/main/app">Github: jonavero</a></p>
    </div>
  </footer>

</html>

app/views/posts/index.html.erb
<div class="container">
  <div class="row">
    <h2 class="titlePost">Posts</h2>

    <div class="col-md-4 inputSearch">
      <%= form_tag root_path, method: :get, :class => 'formulario-buscar  ' do %>
        <%= text_field_tag :search, params[:search], :class => 'inputS fa fa-search', :placeholder => 'Buscar por texto' %>
        <%= submit_tag '', :class => 'fa fa-search noBorden' %>
      <% end %>
    </div>

    <div class="col-md-8 ">

      <%= form_tag root_path, method: :get, :class => ' filterPost' do %>
        <%= collection_select :searchCateg, :searchCateg, Category.all, :id, :description,    {include_blank: true}, { class: "searchCategory"} %>
        <%= submit_tag 'Buscar', :class => 'fa fa-search noBorden' %>
      <% end %>

    </div>
  </div>

  <div class="row">
    <% if @post.empty? %>
      <div class="noFound">
    <h2>Ooops...</h2>
        <p>registro no encontrado</p>
      </div>
      <%end %>
    <% @post.each do |post| %>
      <%=link_to show_path(post) do %>
      <% if (post.id.to_i % 2) == 0 %>
          <div class="col-md-6 card">
            <div class="card2">
            <%= image_tag('imagen.png', size: "250x250",class:"img-rounded imagen") %>
            <h3><%= post.title %></h3>
              <p class="category"> <%=post.category.description %>  </p>
              <p> <%=post.label.description %> </p>

              <div class="row timePost">
                <div class="col-md-6 time1">
                  <p><strong>Creado: </strong> <%=post.created_at.strftime("%-d/%-m/%y: %H:%M ") %></p>

                </div>
                <div class="col-md-6 time2">
                  <p><strong>Actualizado: </strong> <%=post.updated_at.strftime("%-d/%-m/%y: %H:%M") %></p>

                </div>
              </div>


            </div>
        </div>
      <% else %>
        <div class="col-md-6 card">
          <div class="card2">
          <%= image_tag('rails.png', size: "250x250",class: "img-rounded imagen")%>
            <h3><%= post.title %></h3>
            <p class="categoryImpar"> <%=post.category.description %>  </p>
            <p> <%=post.label.description %> </p>

            <div class="row timePost">
              <div class="col-md-6 time1">
                <p><strong> Creado:</strong> <%=post.created_at.strftime("%-d/%-m/%y: %H:%M ") %></p>

              </div>
              <div class="col-md-6 time2">
                <p> <strong> Actualizado:</strong> <%=post.updated_at.strftime("%-d/%-m/%y: %H:%M") %></p>

              </div>
            </div>
          </div>
        </div>
      <% end %>
        <%end %>
    <% end %>
  </div>

    <div class="paginacion ">
      <ul class=" pagination">
        <%= will_paginate @post, renderer: WillPaginate::ActionView::BootstrapLinkRenderer %>
      </ul>
    </div>


</div>

app/views/posts/show.html.erb
<div class="container">
  <div class="banner">
    <%= image_tag ('img.png')  %>
  </div>
  <h2 style="text-align: center"> <%=@post.title %></h2>
  <div class="contenido">
  <p><%=simple_format (@post.body) %></p>
  <div class="row">
    <div class="col-md-6"><strong>Creado: </strong> <%=@post.created_at.strftime("%-d/%-m/%y: %H:%M ") %> </div>
    <div class="col-md-6"><strong>Actualizado: </strong> <%=@post.updated_at.strftime("%-d/%-m/%y: %H:%M ") %></div>
  </div>
  </div>
</div>